# Generated by Django 2.0.7 on 2018-07-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('manager_code', models.IntegerField(primary_key=True, serialize=False)),
                ('manager_name', models.CharField(max_length=50)),
            ],
        ),
    ]
